/*******************************************************************************
 * Copyright 2019 T145
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************/
package t145.tbone.core;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import net.minecraft.block.Block;
import net.minecraft.block.state.IBlockState;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.minecraftforge.common.config.Config;
import net.minecraftforge.common.config.ConfigManager;
import net.minecraftforge.event.world.BlockEvent.NeighborNotifyEvent;
import net.minecraftforge.fml.client.event.ConfigChangedEvent.OnConfigChangedEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerLoggedInEvent;
import t145.tbone.api.config.TConfig;

@Mod(modid = TBone.ID, name = TBone.NAME, version = TBone.VERSION, updateJSON = TBone.UPDATE_JSON)
@EventBusSubscriber
public class TBone {

	public static final String ID = "tbone";
	public static final String NAME = "TBone";
	public static final String VERSION = "@VERSION@";
	public static final String UPDATE_JSON = "https://raw.githubusercontent.com/T145/tbone/master/update.json";
	public static final Logger LOG = LogManager.getLogger(NAME);

	public TBone() {
		TServer.registerMod(ID, NAME);
	}

	@Instance(ID)
	public static TBone instance;

	@EventHandler
	public void tbone$preInit(final FMLPreInitializationEvent event) {
		ModMetadata meta = event.getModMetadata();
		meta.authorList.add("T145");
		meta.autogenerated = false;
		meta.credits = "The fans!";
		meta.description = "Shared code library for my Minecraft mods.";
		meta.logoFile = "logo.png";
		meta.modId = ID;
		meta.name = NAME;
		meta.url = "https://github.com/T145/tbone";
		meta.useDependencyInformation = false;
		meta.version = VERSION;
	}

	@SubscribeEvent
	public static void tbone$configUpdate(final OnConfigChangedEvent event) {
		if (event.getModID().equals(ID)) {
			ConfigManager.sync(ID, Config.Type.INSTANCE);
		}
	}

	@SubscribeEvent
	public static void tbone$playerLogin(final PlayerLoggedInEvent event) {
		if (TConfig.checkForUpdates) {
			for (UpdateChecker mod : TServer.UPDATES) {
				if (mod.hasUpdate()) {
					event.player.sendMessage(mod.getUpdateNotification());
				}
			}
		}
	}

	@SubscribeEvent
	public static void tbone$notifyLeaves(final NeighborNotifyEvent event) {
		if (TConfig.decayLeavesQuickly) {
			World world = event.getWorld();

			for (EnumFacing facing : event.getNotifiedSides()) {
				BlockPos pos = event.getPos().offset(facing);
				IBlockState state = world.getBlockState(pos);
				Block block = state.getBlock();

				if (block.isLeaves(state, world, pos)) {
					world.scheduleUpdate(pos, block, 2 + world.rand.nextInt(6));
				}
			}
		}
	}
}
